#!/usr/bin/python
import socket
import struct
import sys

def cidr_to_netmask(cidr):
    network, net_bits = cidr.split('/')
    host_bits = 32 - int(net_bits)
    netmask = socket.inet_ntoa(struct.pack('!I', (1 << 32) - (1 << host_bits)))
    print network, netmask

if __name__ == "__main__":
    cidr_to_netmask(open(sys.argv[1],'r'))
